# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key     = "non-prod/eu-west-2/stage/kinesis-data-stream/terraform.tfstate"
    region  = "eu-west-2"
    bucket  = "terragrunt-terraform-state-stage-eu-west-2"
    encrypt = true
  }
}
